version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: ${DATASOURCE_BASE:-test}
      POSTGRES_USER: ${DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD:-secret}
      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - D:\pgdata_test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: max@mail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - postgres

volumes:
  pgadmin-data:

networks:
  postgres:
    driver: bridge