server:
  port:
    ${SERVER_PORT}
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
    #default-schema: pet
